packages:
  - 'packages/**'
  - 'sandboxes/**'
  - 'scripts/**'
  - 'website'
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  nx: true
  simple-git-hooks: true
