name: CI

on:
  pull_request:
    branches: [storybook-v7]
  push:
    branches: [storybook-v7]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CI
        uses: ./.github/actions/ci-setup
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint
        run: |
          yarn lint

      - name: Format
        run: |
          yarn format

      - name: Type Check
        run: |
          yarn check

      - name: Check Dependency Version
        run: |
          yarn check-dependency-version

      - name: Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

      - name: Build sandboxes storybooks
        run: |
          yarn build:sandboxes
