name: release

on:
  push:
    branches: [storybook-v7]
  workflow_dispatch:
    inputs:
      pull-request:
        type: number
        description: Pull request number
        required: true

concurrency:
  group: ${{ format('{0} ${1}', github.workflow, case(github.event_name == 'push', github.ref, format('pull_request {0}', inputs.pull-request))) }}
  cancel-in-progress: true

jobs:
  release:
    if: ${{ github.event_name == 'push' && github.repository == 'hextion/storybook-rsbuild' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Generate app token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup CI
        uses: ./.github/actions/ci-setup
        with:
          node-version-file: '.nvmrc'

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: 'yarn release'
          version: 'yarn version-packages'
          commit: 'chore: version-packages'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

  snapshot-release:
    if: ${{ github.event_name == 'workflow_dispatch' && github.repository == 'hextion/storybook-rsbuild' }}
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.snapshot-release.outputs.published }}
      published-packages: ${{ steps.snapshot-release.outputs.published-packages }}
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get ID token
        id: id-token
        uses: actions/github-script@v8
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          result-encoding: string
          script: |
            return await core.getIDToken()

      - name: Get pull request data
        id: data
        uses: actions/github-script@v8
        with:
          script: |
            const { data } = await octokit.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pull-request }},
            })

            core.setOutput('repository', data.head.repo.full_name)
            core.setOutput('sha', data.head.sha)

      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ steps.data.outputs.repository }}
          ref: ${{ steps.data.outputs.sha }}

      - name: Setup CI
        uses: ./.github/actions/ci-setup
        with:
          node-version-file: '.nvmrc'

      - name: Snapshot release
        id: snapshot-release
        uses: core-ds/changesets-snapshot-release@v1
        with:
          version: 'yarn version-packages:snapshot'
          publish: 'yarn release:snapshot'
        env:
          GITHUB_TOKEN: ${{ steps.id-token.outputs.result }}

  comment:
    needs: snapshot-release
    if: ${{ fromJson(needs.snapshot-release.outputs.published) }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Prepare comment
        id: prepare-comment
        uses: actions/github-script@v8
        env:
          PUBLISHED_PACKAGES: ${{ needs.snapshot-release.outputs.published-packages }}
        with:
          result-encoding: string
          script: |
            return JSON.parse(process.env.PUBLISHED_PACKAGES)
                .map(({ name, version }, index) => `${index + 1}. \`${name}@${version}\``)
                .join('\n\n')

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          issue-number: ${{ inputs.pull-request }}
          body: |
            ## Snapshot release

            Successfully released the following packages:

            ${{ steps.prepare-comment.outputs.result }}
