name: Release

on:
  push:
    branches: [storybook-v7]
  workflow_dispatch:
    inputs:
      pull-request:
        type: number
        description: Pull request number
        required: true

concurrency:
  group: ${{ format('{0} ${1}', github.workflow, case(github.event_name == 'push', github.ref, format('pull_request {0}', inputs.pull-request))) }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: generate app token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: hextion
          repositories: storybook-rsbuild

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CI
        uses: ./.github/actions/ci-setup
        with:
          node-version-file: '.nvmrc'

      - name: Create Release Pull Request or Publish to npm
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: 'yarn release'
          version: 'yarn version-packages'
          commit: 'chore: version-packages'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

  snapshot_release:
    name: Snapshot release
    if: ${{ github.event_name == 'workflow_dispatch' && github.repository == 'hextion/storybook-rsbuild' }}
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.snapshot_release.outputs.published }}
      published-packages: ${{ steps.snapshot_release.outputs.published-packages }}
    steps:
      - name: Get pull request data
        id: data
        uses: actions/github-script@v8
        with:
          script: |
            const { data } = await octokit.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pull-request }},
            })

            core.setOutput('repository', data.head.repo.full_name)
            core.setOutput('owner', data.head.repo.owner.login)
            core.setOutput('repo', data.head.repo.name)
            core.setOutput('sha', data.head.sha)

      - name: generate app token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ steps.data.outputs.owner }}
          repositories: ${{ steps.data.outputs.repo }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ steps.data.outputs.repository }}
          ref: ${{ steps.data.outputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup CI
        uses: ./.github/actions/ci-setup
        with:
          node-version-file: '.nvmrc'

      - name: Snapshot release
        id: snapshot_release
        uses: core-ds/changesets-snapshot-release@v1
        with:
          version: 'yarn version-packages:snapshot'
          publish: 'yarn release:snapshot'
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

  comment:
    name: Comment
    needs: snapshot_release
    if: ${{ fromJson(needs.snapshot_release.outputs.published) }}
    runs-on: ubuntu-latest
    permissions:
      issues: write # to post issue comments
    steps:
      - name: Prepare comment
        id: prepare_comment
        uses: actions/github-script@v8
        env:
          PUBLISHED_PACKAGES: ${{ needs.snapshot_release.outputs.published-packages }}
        with:
          result-encoding: string
          script: |
            return JSON.parse(process.env.PUBLISHED_PACKAGES)
                .map(({ name, version }, index) => `${index + 1}. \`${name}@${version}\``)
                .join('\n\n')

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ inputs.pull-request }}
          body: |
            ## Snapshot release

            Successfully released the following packages:

            ${{ steps.prepare_comment.outputs.result }}
          reactions: rocket
